python run.py --forecast_horizon 96 --model_name "AutonLab/MOMENT-1-small" --context_length 512 --seed $RANDOM --device "cuda:1" --dataset_name "ETTh2" --adapter "linearVAE" --use_revin --supervised "ft_then_supervised"
python run.py --forecast_horizon 96 --model_name "AutonLab/MOMENT-1-small" --context_length 512 --seed $RANDOM --device "cuda:1" --dataset_name "ETTh2" --adapter "linearVAE" --use_revin --supervised "ft_then_supervised"
python run.py --forecast_horizon 96 --model_name "AutonLab/MOMENT-1-small" --context_length 512 --seed $RANDOM --device "cuda:1" --dataset_name "ETTh2" --adapter "linearVAE" --use_revin --supervised "ft_then_supervised"
python run.py --forecast_horizon 96 --model_name "AutonLab/MOMENT-1-small" --context_length 512 --seed $RANDOM --device "cuda:1" --dataset_name "ETTh2" --adapter "VAE" --use_revin --supervised "ft_then_supervised"
python run.py --forecast_horizon 96 --model_name "AutonLab/MOMENT-1-small" --context_length 512 --seed $RANDOM --device "cuda:1" --dataset_name "ETTh2" --adapter "VAE" --use_revin --supervised "ft_then_supervised"
python run.py --forecast_horizon 96 --model_name "AutonLab/MOMENT-1-small" --context_length 512 --seed $RANDOM --device "cuda:1" --dataset_name "ETTh2" --adapter "VAE" --use_revin --supervised "ft_then_supervised"
python run.py --forecast_horizon 96 --model_name "AutonLab/MOMENT-1-small" --context_length 512 --seed $RANDOM --device "cuda:1" --dataset_name "ETTh2" --supervised "ft"
python run.py --forecast_horizon 96 --model_name "AutonLab/MOMENT-1-small" --context_length 512 --seed $RANDOM --device "cuda:1" --dataset_name "ETTh2" --supervised "ft"
python run.py --forecast_horizon 192 --model_name "AutonLab/MOMENT-1-small" --context_length 512 --seed $RANDOM --device "cuda:1" --dataset_name "ETTh2" --supervised "ft"
python run.py --forecast_horizon 192 --model_name "AutonLab/MOMENT-1-small" --context_length 512 --seed $RANDOM --device "cuda:1" --dataset_name "ETTh2" --supervised "ft"
