python run.py --forecast_horizon 24 --model_name "AutonLab/MOMENT-1-small" --context_length 512 --seed $RANDOM --device "cuda:6" --dataset_name "Illness" --adapter "linearVAE" --use_revin --supervised "ft_then_supervised"
python run.py --forecast_horizon 24 --model_name "AutonLab/MOMENT-1-small" --context_length 512 --seed $RANDOM --device "cuda:6" --dataset_name "Illness" --adapter "linearVAE" --use_revin --supervised "ft_then_supervised"
python run.py --forecast_horizon 24 --model_name "AutonLab/MOMENT-1-small" --context_length 512 --seed $RANDOM --device "cuda:6" --dataset_name "Illness" --adapter "linearVAE" --use_revin --supervised "ft_then_supervised"
python run.py --forecast_horizon 24 --model_name "AutonLab/MOMENT-1-small" --context_length 512 --seed $RANDOM --device "cuda:6" --dataset_name "Illness" --adapter "VAE" --use_revin --supervised "ft_then_supervised"
python run.py --forecast_horizon 24 --model_name "AutonLab/MOMENT-1-small" --context_length 512 --seed $RANDOM --device "cuda:6" --dataset_name "Illness" --adapter "VAE" --use_revin --supervised "ft_then_supervised"
python run.py --forecast_horizon 24 --model_name "AutonLab/MOMENT-1-small" --context_length 512 --seed $RANDOM --device "cuda:6" --dataset_name "Illness" --adapter "VAE" --use_revin --supervised "ft_then_supervised"
python run.py --forecast_horizon 24 --model_name "AutonLab/MOMENT-1-small" --context_length 512 --seed $RANDOM --device "cuda:6" --dataset_name "Illness" --supervised "ft"
python run.py --forecast_horizon 24 --model_name "AutonLab/MOMENT-1-small" --context_length 512 --seed $RANDOM --device "cuda:6" --dataset_name "Illness" --supervised "ft"
python run.py --forecast_horizon 60 --model_name "AutonLab/MOMENT-1-small" --context_length 512 --seed $RANDOM --device "cuda:6" --dataset_name "Illness" --supervised "ft"
python run.py --forecast_horizon 60 --model_name "AutonLab/MOMENT-1-small" --context_length 512 --seed $RANDOM --device "cuda:6" --dataset_name "Illness" --supervised "ft"
python run.py --forecast_horizon 60 --model_name "AutonLab/MOMENT-1-small" --context_length 512 --seed $RANDOM --device "cuda:6" --dataset_name "Illness" --supervised "ft" --adapter "pca"
python run.py --forecast_horizon 60 --model_name "AutonLab/MOMENT-1-small" --context_length 512 --seed $RANDOM --device "cuda:6" --dataset_name "Illness" --supervised "ft" --adapter "pca"
python run.py --forecast_horizon 60 --model_name "AutonLab/MOMENT-1-small" --context_length 512 --seed $RANDOM --device "cuda:6" --dataset_name "Illness" --supervised "ft" --adapter "pca"
